[tools]
biome = "latest"
docker-compose = "latest"
"github:immanuwell/dockerfile-roast" = "latest"
hk = "latest"
lychee = "latest"
node = "latest"
"npm:@storyteller-platform/align" = "0.2.4"
pixi = "latest"
ruff = "latest"
rumdl = "latest"
shellharden = "latest"
shfmt = "latest"
tombi = "latest"
# Report
typst = "latest"
typstyle = "latest"
