[tools]
# EPUB, Audio & DAISY Pipeline
docker-compose = "latest"
"github:daisy/pipeline-cli-go" = "latest"
"github:immanuwell/dockerfile-roast" = "latest"
"npm:@storyteller-platform/align" = "latest"
# Tools
biome = "latest"
hk = "latest"
# lychee = "latest"
node = "latest"
pixi = "latest"
ruff = "latest"
rumdl = "latest"
shellharden = "latest"
shfmt = "latest"
tombi = "latest"
# Report
typst = "latest"
typstyle = "latest"
