FROM ghcr.io/puppeteer/puppeteer:24.43.1@sha256:75e3404b1df87e39eec2af9fa95e4e0fdbc5c73fc924aafa1429c89a2a3e8654

USER pptruser
WORKDIR /home/pptruser

RUN npm install \
    --save-exact \
    --no-audit \
    --no-fund \
    "@daisy/ace-cli@1.4.6"

WORKDIR /work

ENTRYPOINT ["/home/pptruser/node_modules/.bin/ace-cli"]
CMD ["--help"]
